version: '3.3'

services:

  historia-wordpress:
    depends_on:
      - historia-mysql
    hostname: historia-wordpress
    container_name: historia-wordpress
    #image: wordpress:4.9.4-php7.1-apache
    build: ./
    image: historia:wordpress
    #restart: always
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_HOST: historia-mysql
    volumes:
      - ../:/var/www/html/wp-content/plugins/HistoriaInterface

  historia-mysql:
    hostname: historia-mysql
    container_name: historia-mysql
    image: mysql:5.7
    #restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ~/Dropbox/Data/mysql/historia-mysql:/var/lib/mysql
