version: '3.3'

services:

  historia-wordpress:
    depends_on:
      - historia-mysql
    hostname: historia-wordpress
    container_name: historia-wordpress
    build: ./
    image: historia:wordpress
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_HOST: historia-mysql
    volumes:
      - ../:/var/www/html/wp-content/plugins/HistoriaInterface
      - ~/historia-app/uploads:/var/www/html/wp-content/uploads

  historia-mysql:
    hostname: historia-mysql
    container_name: historia-mysql
    image: mysql:5.7
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ~/historia-app/mysql:/var/lib/mysql
